import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  try {
    console.log('🌱 Iniciando seed de dados...');

    const movies = [
      {
        titulo: 'Inception',
        genero: 'Ficção Científica',
        descricao: 'Um ladrão especializado em roubar segredos corporativos dos inconscientes durante o sono é oferecido a chance de ter seu registro criminal apagado como recompensa.',
        diretor: 'Christopher Nolan',
        elenco: 'Leonardo DiCaprio, Marion Cotillard, Ellen Page',
        duracao: 148,
        anoLancamento: 2010,
        classificacao: 12,
        imagem: 'https://images.unsplash.com/photo-1489599849228-bed96c3f3eff?w=400&h=600&fit=crop',
        nota: 8.8,
        disponivel: true,
      },
      {
        titulo: 'The Shawshank Redemption',
        genero: 'Drama',
        descricao: 'Dois homens presos em uma penitenciária formam uma amizade de longa duração, encontrando consolo e redenção através de atos de decência comum.',
        diretor: 'Frank Darabont',
        elenco: 'Tim Robbins, Morgan Freeman',
        duracao: 142,
        anoLancamento: 1994,
        classificacao: 12,
        imagem: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400&h=600&fit=crop',
        nota: 9.3,
        disponivel: true,
      },
      {
        titulo: 'The Dark Knight',
        genero: 'Ação',
        descricao: 'Quando o Coringa, um criminoso caótico, causa terror em Gotham, Batman enfrenta seu maior desafio para restaurar a ordem à cidade.',
        diretor: 'Christopher Nolan',
        elenco: 'Christian Bale, Heath Ledger, Aaron Eckhart',
        duracao: 152,
        anoLancamento: 2008,
        classificacao: 12,
        imagem: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop',
        nota: 9.0,
        disponivel: true,
      },
      {
        titulo: 'Pulp Fiction',
        genero: 'Crime',
        descricao: 'As vidas de dois assassinos da máfia, uma boxer, a esposa de um chefe do crime e um casal de bandidos se entrelaçam de forma não-linear.',
        diretor: 'Quentin Tarantino',
        elenco: 'John Travolta, Samuel L. Jackson, Uma Thurman',
        duracao: 154,
        anoLancamento: 1994,
        classificacao: 14,
        imagem: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=400&h=600&fit=crop',
        nota: 8.9,
        disponivel: true,
      },
      {
        titulo: 'Forrest Gump',
        genero: 'Drama',
        descricao: 'A vida é como uma caixa de chocolates, você nunca sabe o que vai conseguir. A história extraordinária de um homem com um QI baixo mas com grande determinação.',
        diretor: 'Robert Zemeckis',
        elenco: 'Tom Hanks, Sally Field, Gary Sinise',
        duracao: 142,
        anoLancamento: 1994,
        classificacao: 12,
        imagem: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=400&h=600&fit=crop',
        nota: 8.8,
        disponivel: true,
      },
      {
        titulo: 'The Matrix',
        genero: 'Ficção Científica',
        descricao: 'Um hacker descobre a verdade sobre sua realidade e seu papel no conflito global entre humanos e uma raça de máquinas inteligentes.',
        diretor: 'Lana Wachowski, Lilly Wachowski',
        elenco: 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
        duracao: 136,
        anoLancamento: 1999,
        classificacao: 14,
        imagem: 'https://images.unsplash.com/photo-1533613220915-609f21a91335?w=400&h=600&fit=crop',
        nota: 8.7,
        disponivel: true,
      },
      {
        titulo: 'Interstellar',
        genero: 'Ficção Científica',
        descricao: 'Um time de exploradores viaja através de um buraco de minhoca no espaço para tentar garantir a sobrevivência humana.',
        diretor: 'Christopher Nolan',
        elenco: 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
        duracao: 169,
        anoLancamento: 2014,
        classificacao: 12,
        imagem: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=400&h=600&fit=crop',
        nota: 8.6,
        disponivel: true,
      },
      {
        titulo: 'Gladiador',
        genero: 'Ação',
        descricao: 'Um general romano falsamente acusado de traição luta pela sua liberdade na arena como gladiador enquanto busca vingança.',
        diretor: 'Ridley Scott',
        elenco: 'Russell Crowe, Joaquin Phoenix, Lucilla',
        duracao: 155,
        anoLancamento: 2000,
        classificacao: 14,
        imagem: 'https://images.unsplash.com/photo-1479918419535-c41f63e51c75?w=400&h=600&fit=crop',
        nota: 8.5,
        disponivel: true,
      },
      {
        titulo: 'Toy Story 4',
        genero: 'Animação',
        descricao: 'Quando um novo brinquedo chamado Forky entra em seu grupo, Woody deve embarcar em uma aventura emocionante com seus amigos.',
        diretor: 'Josh Cooley',
        elenco: 'Voz: Tom Hanks, Tim Allen, Annie Potts',
        duracao: 100,
        anoLancamento: 2019,
        classificacao: 6,
        imagem: 'https://images.unsplash.com/photo-1535016120754-fd394db0dda6?w=400&h=600&fit=crop',
        nota: 8.3,
        disponivel: true,
      },
      {
        titulo: 'Avengers: Endgame',
        genero: 'Ação',
        descricao: 'Após os eventos devastadores com Thanos, os Vingadores restantes devem encontrar uma maneira de derrotá-lo e reverter seus atos.',
        diretor: 'Anthony Russo, Joe Russo',
        elenco: 'Robert Downey Jr., Chris Evans, Mark Ruffalo',
        duracao: 181,
        anoLancamento: 2019,
        classificacao: 12,
        imagem: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&h=600&fit=crop',
        nota: 8.4,
        disponivel: true,
      },
      {
        titulo: 'La La Land',
        genero: 'Romance',
        descricao: 'Enquanto perseguem seus sonhos em Los Angeles, um pianista e uma aspirante a atriz se encontram e se apaixonam.',
        diretor: 'Damien Chazelle',
        elenco: 'Ryan Gosling, Emma Stone',
        duracao: 128,
        anoLancamento: 2016,
        classificacao: 12,
        imagem: 'https://images.unsplash.com/photo-1489599849228-bed96c3f3eff?w=400&h=600&fit=crop',
        nota: 8.0,
        disponivel: true,
      },
      {
        titulo: 'Titanic',
        genero: 'Romance',
        descricao: 'Um viajante pobre ganha uma passagem de primeira classe em um navio de luxo e se apaixona por uma jovem noiva.',
        diretor: 'James Cameron',
        elenco: 'Leonardo DiCaprio, Kate Winslet',
        duracao: 194,
        anoLancamento: 1997,
        classificacao: 12,
        imagem: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400&h=600&fit=crop',
        nota: 7.9,
        disponivel: true,
      },
      {
        titulo: 'The Godfather',
        genero: 'Crime',
        descricao: 'O patriarca de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho mais jovem relutante.',
        diretor: 'Francis Ford Coppola',
        elenco: 'Marlon Brando, Al Pacino, James Caan',
        duracao: 175,
        anoLancamento: 1972,
        classificacao: 14,
        imagem: 'https://images.unsplash.com/photo-1489599849228-bed96c3f3eff?w=400&h=600&fit=crop',
        nota: 9.2,
        disponivel: true,
      },
      {
        titulo: 'Jurassic Park',
        genero: 'Ficção Científica',
        descricao: 'Um magnata cria um parque repleto de dinossauros recriados geneticamente, mas tudo sai do controle quando eles escapam.',
        diretor: 'Steven Spielberg',
        elenco: 'Sam Neill, Laura Dern, Jeff Goldblum',
        duracao: 127,
        anoLancamento: 1993,
        classificacao: 12,
        imagem: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop',
        nota: 8.1,
        disponivel: true,
      },
      {
        titulo: 'Avatar',
        genero: 'Ficção Científica',
        descricao: 'Um paralítico marinheiro recebe a chance de habitar um corpo alienígena enquanto os humanos tentam colonizar um planeta extraterrestre.',
        diretor: 'James Cameron',
        elenco: 'Sam Worthington, Zoe Saldana',
        duracao: 162,
        anoLancamento: 2009,
        classificacao: 12,
        imagem: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=400&h=600&fit=crop',
        nota: 7.8,
        disponivel: true,
      },
    ];

    for (const movie of movies) {
      await prisma.movie.create({
        data: movie,
      });
    }

    console.log(`✅ ${movies.length} filmes adicionados com sucesso ao catálogo!`);
  } catch (error) {
    console.error('❌ Erro ao fazer seed:', error);
  } finally {
    await prisma.$disconnect();
  }
}

main();
